

            <h1><?= $cancion->nombre_cancion ?></h1>
    
            
            <h3>Artista: <?= $cancion->artista ?></h3>

            <h3>Álbum: <?= $cancion->album ?></h3>

            <h3>Género: <?= $cancion->genero ?></h3>

            <h3>Año: <?= $cancion->anio ?></h3>

            <h3>Duración: <?= $cancion->duracion ?></h3>

            <h3>Mood: <?= $cancion->mood ?></h3>

            <h3>Link: <?= $cancion->youtube_link ?></h3>

            <h3>Playlist: <?= $cancion->id_playlist ?></h3>
        

   