

<h1>Login</h1>

<?php if (!empty($error)) : ?>
    <div style="color:red;">
        <?= $error ?>
    </div>
<?php endif; ?>

<form method="post" action="verificarLogin">

  <div class="mb-3">
    <label for="Example Email" class="form-label">Usuario</label>
    <input type="input" class="form-control" name="nombre_usuario" id = "id_usuario">  
  </div>

  <div class="mb-3">
    <label for="Example 12345" class="form-label">Password</label>
    <input type="password" class="form-control" name = "password" id="password">
  </div>

  <button type="submit" class="btn btn-primary">Login</button>
</form>

